"""users and post tables

Revision ID: 0f42a91c9509
Revises: 
Create Date: 2021-02-16 14:56:58.537789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f42a91c9509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('audiofile', sa.String(length=64), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_audiofile'), 'sample', ['audiofile'], unique=False)
    op.create_index(op.f('ix_sample_end'), 'sample', ['end'], unique=False)
    op.create_index(op.f('ix_sample_start'), 'sample', ['start'], unique=False)
    op.create_index(op.f('ix_sample_text'), 'sample', ['text'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sample_text'), table_name='sample')
    op.drop_index(op.f('ix_sample_start'), table_name='sample')
    op.drop_index(op.f('ix_sample_end'), table_name='sample')
    op.drop_index(op.f('ix_sample_audiofile'), table_name='sample')
    op.drop_table('sample')
    # ### end Alembic commands ###
