"""sample foreign key

Revision ID: c5b388465f77
Revises: b1910eebbb43
Create Date: 2021-02-16 16:36:11.551287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b388465f77'
down_revision = 'b1910eebbb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'user_id')
    # ### end Alembic commands ###
